### PR TITLE
Add support for changing offsets dynamically

### PR DESCRIPTION
**Pull request by paulinhapenedo**
This PR adds the possibility to change the offsets value dynamically. One case for that would be to change values depending on the viewport size.

It solves #19

### CODE REVIEW

**Comment by stutrek** [comment]
Thanks! OP delivers! Should this also recalculate in case it moved in or out of the viewport?

**Comment by paulinhapenedo** [comment]
No, I don't think so... I mean, I haven't thought about it

**Comment by stutrek** [comment]
I'm pretty sure that if I was using it and a change to the offsets changed the visibility state of the element I'd expect it to call its callbacks. Add these two lines after it to make sure that happens.

```javascript
this.watcher.update();
this.watcher.triggerCallbacks();
```

**Comment by stutrek** [comment]
Thanks for this PR. Published as 2.3.2.

**Comment by wcandillon** [comment]
How can we set visibility offsets? Thank for this great package btw 🙌🏻

**Comment by stutrek** [comment]
Do you mean you want the events to trigger when the component or its parent gets visibility:hidden or display:none?

**Comment by wcandillon** [comment]
@stutrek I would like the event to trigger from instance when 200px of the element has entered the viewport. It seems to be possible to do it with ScrollMonitor but not your react integration?

Thank you for this great component!

**Comment by stutrek** [comment]
It should work if you pass offsets in as a prop. Is it breaking?

**Comment by wcandillon** [comment]
I tried but it didn’t work 🤔 on the Watch component right?

**Comment by wcandillon** [comment]
Thank you for your support! It works great, the issue was in my code 🙈

I reviewed a couple of component like yours and I found yours to be the
best in both the implementation but also in terms of the API you provide,
thank you 🙌🏻

**Pull request merged**
